on:
  push:
    branches: ['main']

env:
  NODE_VERSION: '20.11.1' # set this to the node version to use

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install & build
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        run: |
          curl --request POST \
              --url https://api.render.com/v1/services/${{ secrets.MY_RENDER_SERVICE_ID }}/deploys \
              --header 'accept: application/json' \
              --header 'authorization: Bearer ${{ secrets.MY_RENDER_API_KEY }}' \
              --header 'content-type: application/json' \
              --data '
          {
            "clearCache": "do_not_clear"
          }
          ' --fail-with-body
